name: Jekyll site CI

on:
  push:
    branches: [ "v4" ]
  pull_request:
    branches: [ "v4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby 3.4.x
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set --local path vendor/bundle
        bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build --future
