name: Jekyll site CI

on:
  push:
    branches: [ "v4" ]
  pull_request:
    branches: [ "v4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify Ruby installation
      run: |
        which ruby
        ruby -v

    - name: Install Bundler
      run: |
        sudo gem install bundler

    - name: Install dependencies
      run: |
        bundle config set --local path vendor/bundle
        bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build --future
