name: Jekyll site CI

on:
  push:
    branches: [ "v4" ]
  pull_request:
    branches: [ "v4" ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --platform linux/arm64 -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jvconseil/jekyll-docker:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
